config/routes.rb
  get "sync_management/index"
  post "sync_management/sync"
  get  "sync_management/sync_status"
  get  "sync_management/product_status"
  resources :sync_management, :only => [:destroy]

  get "notices/note_count"
  get "notices/get_new"
  get "notices/auto_complete_search"
  match 'notices/:id/details' => 'notices#details', :via => :get, :as => 'notices_details'
  match 'notices' => 'notices#show', :via => :get
  match 'notices' => 'notices#destroy_all', :via => :delete

  resources :subscriptions, :only => [:index]

  resources :dashboard, :only => [:index]


  resources :systems, :except => [:destroy] do
    member do
      get :packages
      get :more_packages
      get :subscriptions
      post :update_subscriptions
      get :facts
    end
    collection do
      get :auto_complete_search
      get :items
      get :env_items
      get :environments
    end
  end
  resources :operations, :only => [:index]  do
  end

  resources :packages, :only => [:show] do
    member do
      get :changelog
      get :filelist
      get :dependencies
    end
  end

  resources :errata, :only => [:show] do
    member do
      get :packages
    end
  end

  resources :distributions, :only => [:show] do
    member do
      get :filelist
    end
  end

  resources :products, :only => [:new, :create, :edit,:update, :destroy]

  resources :owners do
    member do
      post :import
      get :import_status
    end
  end


  resources :users do
    collection do
      get :auto_complete_search
      get :items
      post :enable_helptip
      post :disable_helptip
    end
    member do
      post :clear_helptips
      put :update_roles
    end
  end

  resources :providers do
    resources :products do
      resources :repositories
    end
    collection do
      get :items
    end
    member do
      get :products_repos
      get :subscriptions
      post :subscriptions, :action=>:update_subscriptions
      get :schedule
    end
  end
  match '/providers/:id' => 'providers#update', :via => :put
  match '/providers/:id' => 'providers#update', :via => :post


  resources :promotions, :only =>[] do
    collection do
      get :index, :action =>:show
    end
    member do
      get :show
      get :products
      get :packages
      get :errata
      get :repos
      get :distributions
      get :details
    end

  end

  match '/organizations/:org_id/environments/:env_id/edit' => 'environments#update', :via => :put
  match '/organizations/:org_id/environments/:env_id/system_templates' => 'environments#system_templates', :via => :get, :as => 'system_templates_organization_environment'

  resources :organizations do
    resources :environments
    resources :providers do
      get 'auto_complete_search', :on => :collection
    end
    resources :providers
    collection do
      get :auto_complete_search
      get :items
    end
  end
  match '/organizations/:id/edit' => 'organizations#update', :via => :put

  resources :changesets, :only => [:update, :index, :show, :create, :new, :edit, :show, :destroy, :auto_complete_search] do
    member do
      put :name
      get :dependencies
      post :promote
      get :object
      get :promotion_progress
    end
    collection do
      get :auto_complete_search
      get :list
      get :items
    end
  end

  resources :environments

  match '/roles/show_permission' => 'roles#show_permission', :via=>:get
  resources :roles do
    put "create_permission" => "roles#create_permission"

    resources :permission, :only => {} do
      delete "destroy_permission" => "roles#destroy_permission", :as => "destroy"
      post "update_permission" => "roles#update_permission", :as => "update"
    end
    collection do
      get :auto_complete_search
      get :items
    end
  end
  match '/roles/:organization_id/resource_type/verbs_and_scopes' => 'roles#verbs_and_scopes', :via=>:get, :as=>'verbs_and_scopes'

  resources :search, :only => {} do
    get 'show', :on => :collection

    get 'history', :on => :collection
    delete 'history' => 'search#destroy_history', :on => :collection

    get 'favorite', :on => :collection
    post 'favorite' => 'search#create_favorite', :on => :collection
    delete 'favorite/:id' => 'search#destroy_favorite', :on => :collection, :as => 'destroy_favorite'
  end


  resource :user_session do
    post 'set_org'
    get 'allowed_orgs'
  end

  resource :account

  root :to => "user_sessions#new"

  match '/login' => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy', :via=>:post
  match '/user_session/logout' => 'user_sessions#destroy'
  match '/user_session' => 'user_sessions#show', :via=>:get, :as=>'show_user_session'



  namespace :api do
    class RegisterWithActivationKeyContraint
      def matches?(request)
        request.params[:activation_keys]
      end
    end
    match '/' => 'root#resource_list'

    resources :systems, :only => [:show, :destroy, :create, :index, :update] do
      member do
        get :packages, :action => :package_profile
        get :errata
      end
    end

    resources :providers, :except => [:index] do
      resources :sync, :only => [:index, :create] do
        delete :index, :on => :collection, :action => :cancel
      end
      member do
        post :import_products
        post :import_manifest
        post :product_create
        get :products
      end
    end

    resources :templates do
      post :promote, :on => :member
      put :update_content, :on => :member
      post :import, :on => :collection
      get :export, :on => :member
    end

    #match '/organizations/:organization_id/locker/repos' => 'environments#repos', :via => :get
    resources :organizations do
      resources :products, :only => [:index] do
        get :repositories, :on => :member
      end
      resources :environments do
        get :repositories, :on => :member
        resources :changesets, :only => [:index, :create]
      end
      resources :tasks, :only => [:index]
      resources :providers, :only => [:index]
      resources :systems, :only => [:index]
      match '/systems' => 'systems#activate', :via => :post, :constraints => RegisterWithActivationKeyContraint.new
      resources :activation_keys, :only => [:index]

      resources :repositories, :only => [] do
        post :discovery, :on => :collection
      end
    end

    resources :changesets, :only => [:show, :destroy] do
      put :update, :on => :member, :action => :update_content
      post :promote, :on => :member, :action => :promote
    end

    resources :products, :only => [:show] do
      get :repositories, :on => :member
      resources :sync, :only => [:index, :create] do
        delete :index, :on => :collection, :action => :cancel
      end
    end

    resources :puppetclasses, :only => [:index]
    resources :ping, :only => [:index]

    resources :repositories, :only => [:index, :show, :create], :constraints => { :id => /[0-9a-zA-Z\-_.]*/ } do
      resources :sync, :only => [:index, :create] do
        delete :index, :on => :collection, :action => :cancel
      end
      resources :packages, :only => [:index]
      resources :errata, :only => [:index]
      resources :distributions, :only => [:index]
      member do
        get :package_groups
        get :package_group_categories
      end
    end

    resources :environments, :only => [:show, :update, :destroy] do
      resources :systems, :only => [:create, :index]
      resources :products, :only => [:index] do
        get :repositories, :on => :member
      end
      resources :activation_keys, :only => [:index, :create]
    end

    resources :activation_keys, :only => [:show, :update, :destroy]
    resources :packages, :only => [:show]
    resources :errata, :only => [:show]
    resources :distributions, :only => [:show]

    resources :users

    resources :tasks, :only => [:show]

    # some paths conflicts with rhsm
    scope 'katello' do

      # routes for non-ActiveRecord-based resources
      match '/products/:id/repositories' => 'products#repo_create', :via => :post, :constraints => { :id => /[0-9\.]*/ }

    end

    # support for rhsm --------------------------------------------------------
    match '/consumers' => 'systems#activate', :via => :post, :constraints => RegisterWithActivationKeyContraint.new
    resources :consumers, :controller => 'systems'
    match '/owners/:organization_id/environments' => 'environments#index', :via => :get
    match '/owners/:organization_id/pools' => 'candlepin_proxies#get', :via => :get
    match '/environments/:environment_id/consumers' => 'systems#index', :via => :get
    match '/environments/:environment_id/consumers' => 'systems#create', :via => :post
    match '/consumers/:id' => 'systems#regenerate_identity_certificates', :via => :post
    match '/users/:username/owners' => 'users#list_owners', :via => :get

    # proxies -------------------
      # candlepin proxy ---------
    match '/consumers/:id/certificates' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:id/certificates/serials' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:id/entitlements' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:id/entitlements' => 'candlepin_proxies#post', :via => :post
    match '/consumers/:id/entitlements' => 'candlepin_proxies#delete', :via => :delete
    match '/consumers/:id/owner' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:consumer_id/certificates/:id' => 'candlepin_proxies#delete', :via => :delete
    match '/pools' => 'candlepin_proxies#get', :via => :get
    match '/entitlements/:id' => 'candlepin_proxies#get', :via => :get
    match '/subscriptions' => 'candlepin_proxies#post', :via => :post

      # pulp proxy --------------
    match '/consumers/:id/profile/' => 'systems#upload_package_profile', :via => :put
    match '/consumers/:id/packages/' => 'systems#upload_package_profile', :via => :put

    # development / debugging support
    get 'status/memory'

app/controllers/api/activation_keys_controller.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

class Api::ActivationKeysController < Api::ApiController
  respond_to :json

  before_filter :verify_presence_of_organization_or_environment, :only => [:index]
  before_filter :find_environment, :only => [:index, :create]
  before_filter :find_organization, :only => [:index]
  before_filter :find_activation_key, :only => [:show, :update, :destroy]
  before_filter :authorize

  def rules
    read_test = lambda{ActivationKey.readable?(@organization)}
    manage_test = lambda{ActivationKey.manageable?(@organization)}
    {
      :index => read_test,
      :show => read_test,
      :create => manage_test,
      :update => manage_test,
      :destroy => manage_test
    }
  end

  def index
    query_params[:organization_id] = @organization.id unless @organization.nil?
    query_params[:environment_id] = @environment.id unless @environment.nil?

    render :json => ActivationKey.where(query_params)
  end

  def show
    render :json => @activation_key
  end

  def create
    created = ActivationKey.create!(params[:activation_key]) do |ak|
      ak.environment = @environment
      ak.organization = @environment.organization
      ak.user = current_user
    end
    render :json => created
  end

  def update
    @activation_key.update_attributes!(params[:activation_key])
    render :json => ActivationKey.find(@activation_key.id)
  end

  def destroy
    @activation_key.destroy
   render :text => _("Deleted activation key '#{params[:id]}'"), :status => 204
  end

  def find_organization
    return unless params.has_key?(:organization_id)

    @organization = Organization.first(:conditions => {:cp_key => params[:organization_id].tr(' ', '_')})
    raise HttpErrors::NotFound, _("Couldn't find organization '#{params[:organization_id]}'") if @organization.nil?
    @organization
  end

  def find_environment
    return unless params.has_key?(:environment_id)

    @environment = KTEnvironment.find(params[:environment_id])
    raise HttpErrors::NotFound, _("Couldn't find environment '#{params[:environment_id]}'") if @environment.nil?
    @environment
  end

  def find_activation_key
    @activation_key = ActivationKey.find(params[:id])
    raise HttpErrors::NotFound, _("Couldn't find activation_key '#{params[:id]}'") if @activation_key.nil?
    @activation_key
  end

  def verify_presence_of_organization_or_environment
    return if params.has_key?(:organization_id) or params.has_key?(:environment_id)
    raise HttpErrors::BadRequest, _("Either organization id or environment id needs to be specified")
  end
end

app/helpers/activation_keys_helper.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

module ActivationKeysHelper

  def no_template
    _("No Template")
  end
  
end

app/views/activation_keys/_edit.html.haml
= javascript :edit_helpers, :activation_key_edit

= javascript do
  :javascript
    localize({
      "edit_environment": '#{_('Edit Environment')}'
    });

= content_for :title do
  #{_("Activation Key")}

= content_for :remove_item do
  - if editable
    = link_to _("Remove Activation Key"), activation_key_path(@activation_key.id), :confirm => _('Are you sure?'), :method => :delete, :class=>"remove_item", :remote=>true

= content_for :navigation do
  = render_navigation(:expand_all => true, :level => 3)

= content_for :content do
  = help_tip_button('activation_keys_edit-help')

  %input#panel_element_id{:name => @activation_key.id, :type => "hidden", :value => "#{name}_#{@activation_key.id}", "data-ajax_url"=>activation_key_path(@activation_key.id)}
  %input#system_templates{ :type => "hidden", :value => @system_templates_json }
  %input#system_templates_temp{ :type => "hidden" }

  #activation_key
    = hidden_field_tag 'environment_id', @activation_key.environment_id

    .grid_10
      = help_tip(_("Edit Activation Key enables you to modify the selected activation key.  This key may " + |
                 "be used during system registration.  For example, <BR/><BR/>" + |
                 "subscription-manager register --org #{@activation_key.organization.name} " + |
                 "--activationkey #{@activation_key.name}"), 'activation_keys_edit-help') |

    .grid_10
      = form_for @activation_key, activation_key_path(@activation_key), :method => "put", :remote => true do |f|
  
        %fieldset.clearfix
          .grid_2.ra
            %label #{_("Name")}:
          .grid_7.la#activation_key_name{'name' => 'activation_key[name]', :class => ("editable edit_panel_element" if editable), 'data-url' => activation_key_path(@activation_key.id)} #{@activation_key[:name]}

        %fieldset.clearfix
          .grid_2.ra
            %label #{_("Description")}:
          .grid_7.la#activation_key_description{:style => "word-wrap: break-word;", 'name' => 'activation_key[description]', :class => ("editable edit_textarea" if editable), 'data-url' => activation_key_path(@activation_key.id)}<> #{@activation_key[:description]}

        %fieldset.promotion_paths
          %label #{_("Select an Environment")}:
          - unless current_organization.environments.empty?
            - current_organization.promotion_paths.each do |path|
              .grid_10
                %ul#env.breadcrumb{:style => 'display: none', :class => ("edit_env_setup" if editable), 'data-env_url' => edit_environment_activation_key_path(@activation_key)}
                  %li
                    = link_to _('Locker'), "#", :class => (editable ? "crumb-editable" : "crumb-nohover")
                  - for env in path
                    %li
                      - if @activation_key.environment_id == env.id
                        %a.selected{'data-env_id' => env.id, :class => (editable ? "crumb-editable-selected" : "crumb-nohover-selected")} #{env.name}
                      - else
                        %a{'data-env_id' => env.id, :class => (editable ? "crumb-editable" : "crumb-nohover")} #{env.name}

        %fieldset.clearfix
          .grid_2.ra
            %label #{_("System Template")}:
          .grid_7.la{'name' => 'activation_key[system_template_id]',  :class => ("editable edit_system_template" if editable), "data-url" => activation_key_path(@activation_key.id)} #{@system_template.nil? ? no_template : @system_template[:name]}

app/views/activation_keys/index.html.haml
= javascript :edit, :multiselect, :form, :activation_key
= include_common_i18n
= include_editable_i18n

= javascript do
  :javascript
    localize({
      "noTemplate": '#{no_template}'
    });

.grid_16
  = help_tip_button
  = help_tip(_("Activation Keys provide a set of characteristics that may be applied to a system " + |
               "during system registration.  This includes things such as, default environment to assign " + |
               "to the system, subscriptions to allocate to the system, system template to apply " + |
               "to the system...etc.")) |

.grid_16#main
  = two_panel(@activation_keys, @panel_options)
  %div#environment_edit_dialog