config/routes.rb
Src::Application.routes.draw do

  resources :activation_keys do
    collection do
      get :auto_complete_search
      get :items
      get :subscriptions
    end
    member do
      get :subscriptions
      get :edit_environment
      post :update
      post :update_subscriptions
    end
  end

  resource :account

  resources :sync_plans, :only => [:index, :create, :new, :edit, :update, :show, :destroy, :auto_complete_search] do
    collection do
      get :auto_complete_search
      get :items
    end
  end

  get  "sync_schedules/index"
  post "sync_schedules/apply"

  get "sync_management/index"
  post "sync_management/sync"
  get  "sync_management/sync_status"
  get  "sync_management/product_status"
  resources :sync_management, :only => [:destroy]

  get "notices/note_count"
  get "notices/get_new"
  get "notices/auto_complete_search"
  match 'notices/:id/details' => 'notices#details', :via => :get, :as => 'notices_details'
  match 'notices' => 'notices#show', :via => :get
  match 'notices' => 'notices#destroy_all', :via => :delete

  resources :subscriptions, :only => [:index]

  resources :dashboard, :only => [:index]


  resources :systems, :except => [:destroy] do
    member do
      get :packages
      get :more_packages
      get :subscriptions
      post :update_subscriptions
      get :facts
    end
    collection do
      get :auto_complete_search
      get :items
      get :env_items
      get :environments
    end
  end
  resources :operations, :only => [:index]  do
  end

  resources :packages, :only => [:show] do
    member do
      get :changelog
      get :filelist
      get :dependencies
    end
  end

  resources :errata, :only => [:show] do
    member do
      get :packages
    end
  end

  resources :distributions, :only => [:show] do
    member do
      get :filelist
    end
  end

  resources :products, :only => [:new, :create, :edit,:update, :destroy]

  resources :owners do
    member do
      post :import
      get :import_status
    end
  end


  resources :users do
    collection do
      get :auto_complete_search
      get :items
      post :enable_helptip
      post :disable_helptip
    end
    member do
      post :clear_helptips
      put :update_roles
    end
  end

  resources :providers do
    resources :products do
      resources :repositories
    end
    collection do
      get :items
    end
    member do
      get :products_repos
      get :subscriptions
      post :subscriptions, :action=>:update_subscriptions
      get :schedule
    end
  end
  match '/providers/:id' => 'providers#update', :via => :put
  match '/providers/:id' => 'providers#update', :via => :post


  resources :promotions, :only =>[] do
    collection do
      get :index, :action =>:show
    end
    member do
      get :show
      get :products
      get :packages
      get :errata
      get :repos
      get :distributions
      get :details
    end

  end

  match '/organizations/:org_id/environments/:env_id/edit' => 'environments#update', :via => :put
  match '/organizations/:org_id/environments/:env_id/system_templates' => 'environments#system_templates', :via => :get, :as => 'system_templates_organization_environment'

  resources :organizations do
    resources :environments
    resources :providers do
      get 'auto_complete_search', :on => :collection
    end
    resources :providers
    collection do
      get :auto_complete_search
      get :items
    end
  end
  match '/organizations/:id/edit' => 'organizations#update', :via => :put

  resources :changesets, :only => [:update, :index, :show, :create, :new, :edit, :show, :destroy, :auto_complete_search] do
    member do
      put :name
      get :dependencies
      post :promote
      get :object
      get :promotion_progress
    end
    collection do
      get :auto_complete_search
      get :list
      get :items
    end
  end

  resources :environments

  match '/roles/show_permission' => 'roles#show_permission', :via=>:get
  resources :roles do
    put "create_permission" => "roles#create_permission"

    resources :permission, :only => {} do
      delete "destroy_permission" => "roles#destroy_permission", :as => "destroy"
      post "update_permission" => "roles#update_permission", :as => "update"
    end
    collection do
      get :auto_complete_search
      get :items
    end
  end
  match '/roles/:organization_id/resource_type/verbs_and_scopes' => 'roles#verbs_and_scopes', :via=>:get, :as=>'verbs_and_scopes'

  resources :search, :only => {} do
    get 'show', :on => :collection

    get 'history', :on => :collection
    delete 'history' => 'search#destroy_history', :on => :collection

    get 'favorite', :on => :collection
    post 'favorite' => 'search#create_favorite', :on => :collection
    delete 'favorite/:id' => 'search#destroy_favorite', :on => :collection, :as => 'destroy_favorite'
  end


  resource :user_session do
    post 'set_org'
    get 'allowed_orgs'
  end

  resource :account

  root :to => "user_sessions#new"

  match '/login' => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy', :via=>:post
  match '/user_session/logout' => 'user_sessions#destroy'
  match '/user_session' => 'user_sessions#show', :via=>:get, :as=>'show_user_session'



  namespace :api do
    class RegisterWithActivationKeyContraint
      def matches?(request)
        request.params[:activation_keys]
      end
    end
    match '/' => 'root#resource_list'

    resources :systems, :only => [:show, :destroy, :create, :index, :update] do
      member do
        get :packages, :action => :package_profile
        get :errata
      end
    end

    resources :providers, :except => [:index] do
      resources :sync, :only => [:index, :create] do
        delete :index, :on => :collection, :action => :cancel
      end
      member do
        post :import_products
        post :import_manifest
        post :product_create
        get :products
      end
    end

    resources :templates do
      post :promote, :on => :member
      put :update_content, :on => :member
      post :import, :on => :collection
      get :export, :on => :member
    end

    #match '/organizations/:organization_id/locker/repos' => 'environments#repos', :via => :get
    resources :organizations do
      resources :products, :only => [:index] do
        get :repositories, :on => :member
      end
      resources :environments do
        get :repositories, :on => :member
        resources :changesets, :only => [:index, :create]
      end
      resources :tasks, :only => [:index]
      resources :providers, :only => [:index]
      resources :systems, :only => [:index]
      match '/systems' => 'systems#activate', :via => :post, :constraints => RegisterWithActivationKeyContraint.new
      resources :activation_keys, :only => [:index]

      resources :repositories, :only => [] do
        post :discovery, :on => :collection
      end
    end

    resources :changesets, :only => [:show, :destroy] do
      put :update, :on => :member, :action => :update_content
      post :promote, :on => :member, :action => :promote
    end

    resources :products, :only => [:show] do
      get :repositories, :on => :member
      resources :sync, :only => [:index, :create] do
        delete :index, :on => :collection, :action => :cancel
      end
    end

    resources :puppetclasses, :only => [:index]
    resources :ping, :only => [:index]

    resources :repositories, :only => [:index, :show, :create], :constraints => { :id => /[0-9a-zA-Z\-_.]*/ } do
      resources :sync, :only => [:index, :create] do
        delete :index, :on => :collection, :action => :cancel
      end
      resources :packages, :only => [:index]
      resources :errata, :only => [:index]
      resources :distributions, :only => [:index]
      member do
        get :package_groups
        get :package_group_categories
      end
    end

    resources :environments, :only => [:show, :update, :destroy] do
      resources :systems, :only => [:create, :index]
      resources :products, :only => [:index] do
        get :repositories, :on => :member
      end
      resources :activation_keys, :only => [:index, :create]
    end

    resources :activation_keys, :only => [:show, :update, :destroy]
    resources :packages, :only => [:show]
    resources :errata, :only => [:show]
    resources :distributions, :only => [:show]

    resources :users

    resources :tasks, :only => [:show]

    # some paths conflicts with rhsm
    scope 'katello' do

      # routes for non-ActiveRecord-based resources
      match '/products/:id/repositories' => 'products#repo_create', :via => :post, :constraints => { :id => /[0-9\.]*/ }

    end

    # support for rhsm --------------------------------------------------------
    match '/consumers' => 'systems#activate', :via => :post, :constraints => RegisterWithActivationKeyContraint.new
    resources :consumers, :controller => 'systems'
    match '/owners/:organization_id/environments' => 'environments#index', :via => :get
    match '/owners/:organization_id/pools' => 'candlepin_proxies#get', :via => :get
    match '/environments/:environment_id/consumers' => 'systems#index', :via => :get
    match '/environments/:environment_id/consumers' => 'systems#create', :via => :post
    match '/consumers/:id' => 'systems#regenerate_identity_certificates', :via => :post
    match '/users/:username/owners' => 'users#list_owners', :via => :get

    # proxies -------------------
      # candlepin proxy ---------
    match '/consumers/:id/certificates' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:id/certificates/serials' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:id/entitlements' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:id/entitlements' => 'candlepin_proxies#post', :via => :post
    match '/consumers/:id/entitlements' => 'candlepin_proxies#delete', :via => :delete
    match '/consumers/:id/owner' => 'candlepin_proxies#get', :via => :get

app/controllers/system_templates_controller.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

class SystemTemplatesController < ApplicationController
  include AutoCompleteSearch

  before_filter :setup_options, :only => [:index, :items]
  before_filter :find_template, :only =>[:update, :edit, :destroy, :show, :object, :update_content]
  before_filter :find_read_only_template, :only =>[:promotion_details]


  #around_filter :catch_exceptions

  def section_id
    'contents'
  end


  def rules

    read_test = lambda{SystemTemplate.readable?(current_organization)}
    manage_test = lambda{SystemTemplate.manageable?(current_organization)}
    {
      :index => read_test,
      :items => read_test,
      :object => read_test,
      :promotion_details => read_test,
      :auto_complete_package => read_test,
      :show => read_test,
      :edit => read_test,
      :product_packages => read_test,
      :update => manage_test,
      :update_content => manage_test,
      :destroy => manage_test,
      :new => manage_test,
      :create => manage_test,
    }
  end


  def index
    @environment = current_organization.locker
    @products = Product.readable(current_organization).joins(:environments).where("environments.id = #{@environment.id}")
    @templates = SystemTemplate.search_for(params[:search]).where(:environment_id => current_organization.locker.id).limit(current_user.page_size)

    product_hash = {}
    @products.each{|prd|  product_hash[prd.name] = prd.id}

    retain_search_history
    render :index, :locals=>{:editable=>SystemTemplate.manageable?(current_organization), :product_hash => product_hash}
  end
  
  def items
    start = params[:offset]
    @templates = SystemTemplate.readable(current_organization).search_for(params[:search]).limit(current_user.page_size).offset(start)
    render_panel_items @templates, @panel_options
  end
  
  def setup_options
    columns = ['name']
    @panel_options = { :title => _('System Templates'),
                 :col => columns,
                 :create => _('Template'),
                 :name => _('template'),
                 :ajax_scroll => items_system_templates_path(),
                 :enable_create => SystemTemplate.manageable?(current_organization) }
  end


  def object
    pkgs = @template.packages.collect{|pkg| {:name=>pkg.package_name}}
    products = @template.products.collect{|prod| {:name=>prod.name, :id=>prod.id}}
    to_ret = {:id=> @template.id, :name=>@template.name, :description=>@template.description,
              :packages=>pkgs, :products=>products}
    render :json=>to_ret
  end

  def edit
    render :partial => "edit", :layout => "tupane_layout",
           :locals => {:template=>@template, :editable=> SystemTemplate.editable? }
  end


  def product_packages
    @product = Product.readable(current_organization).find(params[:product_id])
      @packages = []
      @product.repos(current_organization.locker).each{|repo|
        repo.packages.each{|pkg|
          @packages << pkg.name
        }
      }


    @packages.sort!.uniq!
    offset = params[:offset].to_i if params[:offset]

    if offset
      @packages = @packages[offset..offset+current_user.page_size]
      render :text=>"" and return if @packages.empty?
    else
      @packages = @packages[0..current_user.page_size]
    end

    render :partial=>"product_packages"

  end

  def update_content
    pkgs = params[:packages]
    products = params[:products]

    @template.packages.delete_all
    pkgs.each{|pkg|
      @template.packages << SystemTemplatePackage.new(:system_template=>@template, :package_name=>pkg[:name])
    }

    @template.products = []
    products.each{|prod|
      @template.products << Product.readable(current_organization).find(prod[:id])
    }
    
    @template.save!
    notice _("Template #{@template.name} has been updated successfully")
    object()
  end

  def update
    attrs = params[:system_template]
    if attrs[:name]
      result = @template.name = attrs[:name]
    elsif attrs[:description]
      result = @template.description = attrs[:description]
    end
    @template.save!
    notice _("Template #{@template.name} updated successfully.")
    render :text=>result

  rescue Exception => e
    errors e
    render :text=>e, :status=>:bad_request
  end

  def destroy
      
      @template.destroy
      notice _("Template '#{@template.name}' was deleted.")
      render :partial => "common/list_remove", :locals => {:id => @template.id, :name=>"details"}
  rescue Exception => e
      errors e.to_s
      render :text=> e, :status=>:bad_request
  end

  def show
    render :partial => "common/list_update", :locals=>{:item=>@template, :accessor=>"id", :columns=>['name']}
  end

  def new
    @template = SystemTemplate.new
    render :partial => "new", :layout => "tupane_layout", :locals => {:template => @template}
  end

  def promotion_details
    render :partial => "promotion_details", :layout => "tupane_layout", :locals=>{:template=>@template}
  end

  def auto_complete_package
    name = params[:name]
    render :json=>Pulp::Package.name_search(name).sort.uniq[0..19]
  end

  def create
    
    obj_params = params[:system_template]
    obj_params[:environment_id] = current_organization.locker.id

    @template = SystemTemplate.create!(obj_params)
    notice _("Sync Plan '#{@template.name}' was created.")
    render :json=>{:name=>@template.name, :id=>@template.id}

  rescue Exception => e
    errors e
    render :text => e, :status => :bad_request
  end
  
  protected

  def find_read_only_template
    @template = SystemTemplate.find(params[:id])
  end

  def find_template
    find_read_only_template
    raise _("Cannot modify a template that is another environment") if !@template.environment.locker?
  rescue Exception => e
    errors e
    render :text=>e, :status=>400 and return false
  end

end

app/helpers/system_templates_helper.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

module SystemTemplatesHelper
  include ActionView::Helpers::JavaScriptHelper

  include BreadcrumbHelper::TemplateContentBreadcrumb



end

app/views/system_templates/_edit.html.haml
.grid_7#plan
  %fieldset.fl.clear
    %label.grid_2 #{_("Name")}:
    .grid_4.la#edit_template_name{'name' => 'system_template[name]', :class=>("editable edit_template_name" if editable)} "FOO "
  %fieldset.fl.clear
    %label.grid_2 #{_("Description")}:
    .grid_4.la#edit_template_description{'name' => 'system_template[description]', :class=>("editable edit_template_description" if editable)} "FOO "

app/views/system_templates/_new.html.haml
.grid_7
  = form_for SystemTemplate.new, :html => {:method => :post, :id => 'new_system_template'}, :url => system_templates_path do |form|
    %fieldset.fl.clear
      %label.grid_2 #{_("Name")}:
      .grid_4.la#template_name
        = form.text_field :name

    %fieldset.fl.clear
      %label.grid_2 #{_("Description")}:
      .grid_4.la#template_description
        = form.text_area :description, :cols=>30, :rows=>5


    .grid_3.la.prefix_2
      = button_to _("Save"), {:action => "create", :controller => "system_templates"}, :method => :post, :id => :template_save

app/views/system_templates/_product_packages.html.haml
%ul.expand_list
  -if @packages.empty?
    #{_("No packages available.")}
  - @packages.each do |pack|
    %li
      %a{:class => "fr package_add_remove st_button", "data-name"=> pack, :id => "add_remove_package_#{pack}"}= "+ #{_("Add")}"
      .no_slide
        %span.block{"data-name"=>pack}
          = pack

app/views/system_templates/_products.html.haml
%ul.expand_list
  -if products.empty?
    #{_("No products")}
  -for product in products
    %li.clear.slide_link
      %a.product_add_remove.st_button.fr{ "data-id" => product.id, "data-name"=>product.name}
        = "+ #{_("Add")}"
      .link_details{:id=>packages_bc_id(product)}
        - if product.provider.provider_type == Provider::REDHAT
          %span.rh-product-sprite
        - else
          %span.custom-product-sprite
        %span.product-icon{:style=>"display: inline;"}
          #{product.name}&nbsp;
          - for arch in product.repos(@environment).collect{|repo| repo.arch }.uniq
            .product_arch
              = arch



%br.clear

app/views/system_templates/_promotion_details.html.haml
= javascript :system_template_promotion

= content_for :title do
  = template.name

= content_for :content do
  .clear
  %fieldset.grid_5
    %label #{_("Name")}:
    = template.name
  #system_template_promotion_tabs
    .grid_5
      %h5 #{_("Contents:")}
      -if template.products.empty? && template.packages.empty?
        .grid_2.prefix_1
          #{_("This template contains no content.")}
      -else
        #system_template_accordion.grid_7.system_templates_tab
          - unless template.products.empty?
            %h3
              %a{:href=>'#'}= _("Products")
            #system_templates.system_templates_tab
              %ul
                -for prod in template.products
                  %li #{prod.name}
          - unless template.packages.empty?
            %h3
              %a{:href=>'#'}= _("Packages")
            .system_templates_tab
              %ul.package_item_entry
                - template.packages.each do |package|
                  %li
                    = package.package_name

app/views/system_templates/index.html.haml
= javascript :panel, :edit, :system_template
= include_editable_i18n




= javascript do
  :javascript

    KT.permissions = {
      editable: #{editable}
    }
    KT.content_breadcrumb = $.parseJSON('#{escape_javascript(template_content_breadcrumb())}');
    KT.template_breadcrumb = $.parseJSON('#{escape_javascript(generate_template_breadcrumb())}');
    KT.product_hash = $.parseJSON('#{escape_javascript(product_hash.to_json)}');
    localize({
      "add": '+ #{_('Add')}',
      "add_plus": '+ #{_('Add')}',
      "remove": '#{_('Remove')}',
      "products": '#{_('Products')}',
      "packages": '#{_('Packages')}',
      "edit_label": '#{_("Edit Details")}',
      "edit_close_label": '#{_("Close Edit")}',
      "add_label": '#{_("Add")}',
      "add_close_label": '#{_("Cancel Add")}',
      "templates_empty": '#{_("No System Templates are currently defined")}',
      "save" : '#{_("Save")}',
      "package_search_text": '#{_("Search available package names...")}',
      "product_search_text": '#{_("Search available product names...")}',
      "modify_message": '#{_('The current template "$TEMPLATE" has been modified.  Would you like to save the changes?')}',
      "leave_page": '#{_('The current template "$TEMPLATE" has been modified. If you leave, any changes will be lost."')}'
      });


= help_tip_button
.grid_16
  = help_tip(_('System Templates allow you to create a template for what a system should look like.  This includes what ' + |
               'products are subscribed and what packages are installed.'))   |


.grid_16
  #container


    .right_tree.sliding_tree
      #template_tree
        %h2= _("System Templates")
        .breadcrumb_search.fl.clear.clickable
          %form#search_form.search.clear
            %input{ :name => "s", :type => "input", :placeholder => "Filter...", :id=>"search_filter"}
            %button.action #{_("Search")}
            %br.clear

          .search_button.fr.clickable
            #{_('Search')}

          .tree_breadcrumb.clickable.clear
        .sliding_container
          #template_list.list.sliding_list{"data-page_size"=>current_user.page_size}
            #tree_loading.slider.tree_loading
              .text
                = _("Loading System Template")
                = image_tag ("spinner.gif")
            #tree_saving.slider.tree_loading
              .text
                = _("Saving System Template")
                = image_tag ("spinner.gif")
            .slider_one.has_content.slider.will_have_content
            .slider_two.no_content.slider


        #add_template_container.slide_up_container
          %h2= _("New System Template")
          = render :partial=>"new"

        #edit_template_container.slide_up_container
          %h2= _("Edit System Template")
          = render :partial=>"edit", :locals=>{:editable=>true}
        - if editable
          #sliding_tree_actionbar.clickable
            #add_template.cs_action
              %span#add_template_icon.sprite
                SPRITE
              %span.text
                = _("Add")
            #edit_template.cs_action
              %span#edit_template_icon.sprite
                SPRITE
              %span.text
                = _("Edit Details")
            #remove_template.cs_action{ "data-confirm-text" => "#{_('Are you sure you want to remove this template?')}" }
              %span#remove_template_icon.sprite
                SPRITE
              %span.text
                = _("Remove")
            #save_template.cs_action.disabled
              %span#save_template_icon.sprite
                SPRITE
              %span.text
                = _("Save")



    = render :partial=>"common/tupane"
    #content_tree.left.sliding_tree
      %h2= _("Eligible Content")
      .tree_breadcrumb.clickable.clear
      .sliding_container
        #list.list.sliding_list{"data-page_size"=>current_user.page_size}
          .slider_one.has_content.slider
          .slider_two.no_content.slider



#error_dialog{:style=>"display: none"}
  = _("An error has occured when communicating with the server, please refresh the page to retrieve the current System Template")

#modified_dialog{:style=>"display: none"}
  %div.text
  %input#discard_dialog.button.fr{:type => "button", :value=>"#{('Discard Changes')}"}
  %input#save_dialog.button.fr{:type => "button", :value=>"#{('Save Changes')}"}