config/routes.rb
      get :edit_environment
      post :update
      post :update_subscriptions
    end
  end

  resource :account

  resources :sync_plans, :only => [:index, :create, :new, :edit, :update, :show, :destroy, :auto_complete_search] do
    collection do
      get :auto_complete_search
      get :items
    end
  end

  get  "sync_schedules/index"
  post "sync_schedules/apply"

  get "sync_management/index"
  post "sync_management/sync"
  get  "sync_management/sync_status"
  get  "sync_management/product_status"
  resources :sync_management, :only => [:destroy]

  get "notices/note_count"
  get "notices/get_new"
  get "notices/auto_complete_search"
  match 'notices/:id/details' => 'notices#details', :via => :get, :as => 'notices_details'
  match 'notices' => 'notices#show', :via => :get
  match 'notices' => 'notices#destroy_all', :via => :delete

  resources :subscriptions, :only => [:index]

  resources :dashboard, :only => [:index]


  resources :systems, :except => [:destroy] do
    member do
      get :packages
      get :more_packages
      get :subscriptions
      post :update_subscriptions
      get :facts
    end
    collection do
      get :auto_complete_search
      get :items
      get :env_items
      get :environments
    end
  end
  resources :operations, :only => [:index]  do
  end

  resources :packages, :only => [:show] do
    member do
      get :changelog
      get :filelist
      get :dependencies
    end
  end

  resources :errata, :only => [:show] do
    member do
      get :packages
    end
  end

  resources :distributions, :only => [:show] do
    member do
      get :filelist
    end
  end

  resources :products, :only => [:new, :create, :edit,:update, :destroy]

  resources :owners do
    member do
      post :import
      get :import_status
    end
  end


  resources :users do
    collection do
      get :auto_complete_search
      get :items
      post :enable_helptip
      post :disable_helptip
    end
    member do
      post :clear_helptips
      put :update_roles
    end
  end

  resources :providers do
    resources :products do
      resources :repositories
    end
    collection do
      get :items
    end
    member do
      get :products_repos
      get :subscriptions
      post :subscriptions, :action=>:update_subscriptions
      get :schedule
    end
  end
  match '/providers/:id' => 'providers#update', :via => :put
  match '/providers/:id' => 'providers#update', :via => :post


  resources :promotions, :only =>[] do
    collection do
      get :index, :action =>:show
    end
    member do
      get :show
      get :products
      get :packages
      get :errata
      get :repos
      get :distributions
      get :details
    end

  end

  match '/organizations/:org_id/environments/:env_id/edit' => 'environments#update', :via => :put
  match '/organizations/:org_id/environments/:env_id/system_templates' => 'environments#system_templates', :via => :get, :as => 'system_templates_organization_environment'

  resources :organizations do
    resources :environments
    resources :providers do
      get 'auto_complete_search', :on => :collection
    end
    resources :providers
    collection do
      get :auto_complete_search
      get :items
    end
  end
  match '/organizations/:id/edit' => 'organizations#update', :via => :put

  resources :changesets, :only => [:update, :index, :show, :create, :new, :edit, :show, :destroy, :auto_complete_search] do
    member do
      put :name
      get :dependencies
      post :promote
      get :object
      get :promotion_progress
    end
    collection do
      get :auto_complete_search
      get :list
      get :items
    end
  end

  resources :environments

  match '/roles/show_permission' => 'roles#show_permission', :via=>:get
  resources :roles do
    put "create_permission" => "roles#create_permission"

    resources :permission, :only => {} do
      delete "destroy_permission" => "roles#destroy_permission", :as => "destroy"
      post "update_permission" => "roles#update_permission", :as => "update"
    end
    collection do
      get :auto_complete_search
      get :items
    end
  end
  match '/roles/:organization_id/resource_type/verbs_and_scopes' => 'roles#verbs_and_scopes', :via=>:get, :as=>'verbs_and_scopes'

  resources :search, :only => {} do
    get 'show', :on => :collection

    get 'history', :on => :collection
    delete 'history' => 'search#destroy_history', :on => :collection

    get 'favorite', :on => :collection
    post 'favorite' => 'search#create_favorite', :on => :collection
    delete 'favorite/:id' => 'search#destroy_favorite', :on => :collection, :as => 'destroy_favorite'
  end


  resource :user_session do
    post 'set_org'
    get 'allowed_orgs'
  end

  resource :account

  root :to => "user_sessions#new"

  match '/login' => 'user_sessions#new'
  match '/logout' => 'user_sessions#destroy', :via=>:post
  match '/user_session/logout' => 'user_sessions#destroy'
  match '/user_session' => 'user_sessions#show', :via=>:get, :as=>'show_user_session'



  namespace :api do
    class RegisterWithActivationKeyContraint
      def matches?(request)
        request.params[:activation_keys]
      end
    end
    match '/' => 'root#resource_list'

    resources :systems, :only => [:show, :destroy, :create, :index, :update] do
      member do
        get :packages, :action => :package_profile
        get :errata
      end
    end

    resources :providers, :except => [:index] do
      resources :sync, :only => [:index, :create] do
        delete :index, :on => :collection, :action => :cancel
      end
      member do
        post :import_products
        post :import_manifest
        post :product_create
        get :products
      end
    end

    resources :templates do
      post :promote, :on => :member
      put :update_content, :on => :member
      post :import, :on => :collection
      get :export, :on => :member
    end

    #match '/organizations/:organization_id/locker/repos' => 'environments#repos', :via => :get
    resources :organizations do
      resources :products, :only => [:index] do
        get :repositories, :on => :member
      end
      resources :environments do
        get :repositories, :on => :member
        resources :changesets, :only => [:index, :create]
      end
      resources :tasks, :only => [:index]
      resources :providers, :only => [:index]
      resources :systems, :only => [:index]
      match '/systems' => 'systems#activate', :via => :post, :constraints => RegisterWithActivationKeyContraint.new
      resources :activation_keys, :only => [:index]

      resources :repositories, :only => [] do
        post :discovery, :on => :collection
      end
    end

    resources :changesets, :only => [:show, :destroy] do
      put :update, :on => :member, :action => :update_content
      post :promote, :on => :member, :action => :promote
    end

    resources :products, :only => [:show] do
      get :repositories, :on => :member
      resources :sync, :only => [:index, :create] do
        delete :index, :on => :collection, :action => :cancel
      end
    end

    resources :puppetclasses, :only => [:index]
    resources :ping, :only => [:index]

    resources :repositories, :only => [:index, :show, :create], :constraints => { :id => /[0-9a-zA-Z\-_.]*/ } do
      resources :sync, :only => [:index, :create] do
        delete :index, :on => :collection, :action => :cancel
      end
      resources :packages, :only => [:index]
      resources :errata, :only => [:index]
      resources :distributions, :only => [:index]
      member do
        get :package_groups
        get :package_group_categories
      end
    end

    resources :environments, :only => [:show, :update, :destroy] do
      resources :systems, :only => [:create, :index]
      resources :products, :only => [:index] do
        get :repositories, :on => :member
      end
      resources :activation_keys, :only => [:index, :create]
    end

    resources :activation_keys, :only => [:show, :update, :destroy]
    resources :packages, :only => [:show]
    resources :errata, :only => [:show]
    resources :distributions, :only => [:show]

    resources :users

    resources :tasks, :only => [:show]

    # some paths conflicts with rhsm
    scope 'katello' do

      # routes for non-ActiveRecord-based resources
      match '/products/:id/repositories' => 'products#repo_create', :via => :post, :constraints => { :id => /[0-9\.]*/ }

    end

    # support for rhsm --------------------------------------------------------
    match '/consumers' => 'systems#activate', :via => :post, :constraints => RegisterWithActivationKeyContraint.new
    resources :consumers, :controller => 'systems'
    match '/owners/:organization_id/environments' => 'environments#index', :via => :get
    match '/owners/:organization_id/pools' => 'candlepin_proxies#get', :via => :get
    match '/environments/:environment_id/consumers' => 'systems#index', :via => :get
    match '/environments/:environment_id/consumers' => 'systems#create', :via => :post
    match '/consumers/:id' => 'systems#regenerate_identity_certificates', :via => :post
    match '/users/:username/owners' => 'users#list_owners', :via => :get

    # proxies -------------------
      # candlepin proxy ---------
    match '/consumers/:id/certificates' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:id/certificates/serials' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:id/entitlements' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:id/entitlements' => 'candlepin_proxies#post', :via => :post
    match '/consumers/:id/entitlements' => 'candlepin_proxies#delete', :via => :delete
    match '/consumers/:id/owner' => 'candlepin_proxies#get', :via => :get
    match '/consumers/:consumer_id/certificates/:id' => 'candlepin_proxies#delete', :via => :delete
    match '/pools' => 'candlepin_proxies#get', :via => :get

app/controllers/api/changesets_controller.rb
#
# Copyright 2011 Red Hat, Inc.
#
# This software is licensed to you under the GNU General Public
# License as published by the Free Software Foundation; either version
# 2 of the License (GPLv2) or (at your option) any later version.
# There is NO WARRANTY for this software, express or implied,
# including the implied warranties of MERCHANTABILITY,
# NON-INFRINGEMENT, or FITNESS FOR A PARTICULAR PURPOSE. You should
# have received a copy of GPLv2 along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

class Api::ChangesetsController < Api::ApiController

  before_filter :find_environment, :only => [:index, :create]
  before_filter :find_changeset, :only => [:show, :destroy, :update_content, :promote]
  before_filter :authorize

  def rules
    read_perm = lambda{@environment.changesets_readable?}
    manage_perm = lambda{@environment.changesets_manageable?}
    promote_perm = lambda{@environment.changesets_promotable?}
    {
      :index => read_perm,
      :show => read_perm,
      :create => manage_perm,
      :promote => promote_perm,
      :destroy =>manage_perm,
      :update_content => manage_perm,
    }
  end 

  respond_to :json

  def index
    render :json => Changeset.select("changesets.*, environments.name AS environment_name").joins(:environment).where(params.slice(:name, :environment_id))
  end


  def show
    render :json => @changeset.to_json(:include => [:products, :packages, :errata, :repos])
  end


  def create
    @changeset = Changeset.new(params[:changeset])
    @changeset.environment = @environment
    @changeset.save!

    render :json => @changeset
  end

  def promote
    @changeset.state = Changeset::REVIEW
    @changeset.save!
    async_job = @changeset.async(:organization => @changeset.environment.organization).promote
    render :json => async_job, :status => 202
  end

  def destroy
    @changeset.destroy
    render :text => _("Deleted changeset '#{params[:id]}'"), :status => 200
  end


  def update_content

    each_patch_item '+products' do |name| @changeset.add_product name end
    each_patch_item '-products' do |name| @changeset.remove_product name end

    each_patch_item '+packages' do |rec| @changeset.add_package rec[:name], rec[:product] end
    each_patch_item '-packages' do |rec| @changeset.remove_package rec[:name], rec[:product] end

    each_patch_item '+errata' do |rec| @changeset.add_erratum rec[:name], rec[:product] end
    each_patch_item '-errata' do |rec| @changeset.remove_erratum rec[:name], rec[:product] end

    each_patch_item '+repos' do |rec| @changeset.add_repo rec[:name], rec[:product] end
    each_patch_item '-repos' do |rec| @changeset.remove_repo rec[:name], rec[:product] end

    @changeset.save!
    render :json => @changeset.to_json(:include => [:products, :packages, :errata, :repos])
  end

  def each_patch_item name, &block
    return if params[:patch].nil? or params[:patch][name].nil?

    params[:patch][name].each do |rec|
      yield rec
    end
  end

  def find_changeset
    @changeset = Changeset.find(params[:id])
    raise HttpErrors::NotFound, _("Couldn't find changeset '#{params[:id]}'") if @changeset.nil?
    @environment = @changeset.environment
    @changeset
  end


  def find_environment
    @environment = KTEnvironment.find(params[:environment_id])
    raise HttpErrors::NotFound, _("Couldn't find environment '#{params[:environment_id]}'") if @environment.nil?
    @environment
  end

end

app/views/changesets/_content_type.html.haml
//requierd local vars:
// type_string   - i18n string of of what type to show
//  items  -  list of items for that list
- if !items.empty?
  %div.content_group
    .grid_5
      %a.clickable{ :href => "#", :onclick => ""}
        = image_tag('icons/expander-collapsed.png', :alt => _('Expand'))
      = type_string
    .grid_5.cs_content{:style=>"display: none;"}
      %ul.cs_history_entry
        - for item in items
          %li
            = item

app/views/changesets/_dependency_list.html.haml
- for dep in @packages
  %li
    = dep.nvrea

app/views/changesets/_edit.html.haml
//Edit/view page as seen on the 2 pane changeset history list
= javascript :changeset_edit


= content_for :title do
  = _("Details")

= content_for :content do
  .grid_10
    #changeset.fieldset{'data-ajax_url'=>changeset_path(@changeset.id)}
      .grid_2.ra
        %label #{_("Name:")}
      .grid_7.la{:name=>"name", :class=>("editable edit_textfield" if editable), "data-id"=>@changeset.id,"data-url"=>changeset_path(@changeset.id)} #{@changeset.name}

    #changeset.fieldset{'data-ajax_url'=>changeset_path(@changeset.id)}
      .grid_2.ra
        %label #{_("Description:")}
      .grid_7.la{:name=>"description", :class=>("editable edit_description" if editable), "data-id"=>@changeset.id,"data-url"=>changeset_path(@changeset.id)} #{@changeset.description}




    .fieldset
      .grid_2.ra
        %label #{_("Promotion Date:")}
      .grid_7.la
        = I18n.l(@changeset.promotion_date, :format=>:long)
    #changeset_history_tabs
      .grid_10
        %h2 #{_("Contents:")}
        -if @changeset.involved_products.empty? && @changeset.system_templates.empty?
          .grid_7.prefix_1
            #{_("This changeset contains no content.")}
        -else
          #accordion.grid_8.prefix_1.cs_history_tab
            - if !@changeset.system_templates.empty?
              %h3
                %a{:href=>'#'}= _("System Templates")
              #system_templates.cs_history_tab
                %ul
                -for template in @changeset.system_templates
                  %li
                    = template.name

            - if !@changeset.products.empty?
              %h3
                %a{:href=>'#'} #{_("Full Products")}
              #full_products.cs_history_tab
                %ul
                  -for prod in @changeset.products
                    %li #{prod.name}
            - for prod in @changeset.partial_products
              %h3
                %a{:href=>'#'} #{_(prod.name)}
              .cs_history_tab
                = render :partial=>"content_type", :locals=>{:items=>@changeset.packages.where(:product_id=>prod.id).collect{|i| i.display_name},
                                                              :type_string=>_("Packages")}
                = render :partial=>"content_type", :locals=>{:items=>@changeset.errata.where(:product_id=>prod.id).collect{|i| i.display_name},
                                                              :type_string=>_("Errata")}
                = render :partial=>"content_type", :locals=>{:items=>@changeset.repos.where(:product_id=>prod.id).collect{|i| i.display_name},
                                                              :type_string=>_("Repositories")}

app/views/changesets/_list.html.haml
- for item in @changesets
  = render :partial=>"common/list_item", :locals=>{:item=>item, :accessor=>:id, :columns=>@columns, :name=>name}

app/views/changesets/_name.html.haml
%fieldset
  .grid_3.ra
    = label_tag :name, _("Name:")
  .grid_4.la
    %input.changeset_name{ :id => "name", :name => "name", :type => "text", :value => @changeset.name, "data-environment_id" => @environment.id }

app/views/changesets/_new.html.haml
= content_for :title do
  #{_("New Changeset")}

= content_for :navigation do
  / pretty

= content_for :content do
  .grid_8#new_changeset123
    -if @next_environment
      = form_tag changesets_path, :method => "post", :id => "new_changeset" do
        %input{ :type => "hidden", :name => "env_id", :value => @environment.id }
        %input{ :type => "hidden", :name => "next_env_id", :value => @next_environment.id }
        %fieldset
          .grid_2.ra
            %label #{_("Name")}:
          .grid_4.la
            = text_field_tag :name, params[:name], :tabindex => auto_tab_index
        %filedset
          .grid_2.ra
            %label #{_("Description")}:
          .grid_4.la
            = text_area_tag :description, nil, :tabindex => auto_tab_index
        .grid_5.ra
          .button#save_changeset_button{'data-url' => changesets_path, :tabindex => auto_tab_index}
            #{_("Save Changeset")}
    -else
      #{_("Cannot create a new changeset without a next environment to promote in to. <br> Create a next environment on the organization screen.")}

app/views/changesets/index.html.haml
= include_editable_i18n


.grid_16
  = environment_selector(:locker_clickable=>false, :accessible_envs=>accessible_envs)
.grid_16
  = two_panel(@changesets, @panel_options)


= javascript :edit, :changeset